import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:syntrak/core/theme.dart';
import 'package:syntrak/models/profile.dart';
import 'package:syntrak/providers/auth_provider.dart';
import 'package:syntrak/services/api_service.dart';
import 'package:syntrak/screens/profile/edit_profile_screen.dart';

/// ProfileHeader is a widget that displays the profile information at the top of the profile screen
/// use query to fetch and cache profile information from the backend

class ProfileHeader extends StatefulWidget {
  final String? userId; // If null, shows current user's profile
  // profile header widget = used to display the profile information

  const ProfileHeader({
    super.key,

    /// key for the widget, generated by the framework
    this.userId,
  });

  @override

  /// change the behavior of methods in a child class that were originially defined in a parent class
  State<ProfileHeader> createState() => _ProfileHeaderState();
}

class _ProfileHeaderState extends State<ProfileHeader> {
  Profile? _profile;
  bool _isLoading = true;
  String? _error;
  bool _hasLoaded = false;
  String? _lastUserId;

  @override
  void initState() {
    super.initState();
    _lastUserId = widget.userId;
    _loadProfile();
  }

  @override
  void didUpdateWidget(ProfileHeader oldWidget) {
    super.didUpdateWidget(oldWidget);
    // Only reload if userId changed
    if (oldWidget.userId != widget.userId) {
      _lastUserId = widget.userId;
      _hasLoaded = false;
      _loadProfile();
    }
  }

  Future<void> _loadProfile() async {
    // Prevent multiple simultaneous loads
    if (_isLoading && _hasLoaded) {
      print('🔍 [ProfileHeader] Skipping load - already loading and loaded');
      return;
    }

    print('🔍 [ProfileHeader] Loading profile...');
    setState(() {
      _isLoading = true;
      _error = null;
    });

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final apiService = ApiService();

    // Check if session exists
    if (authProvider.session == null) {
      print('🔍 [ProfileHeader] No session available');
      if (mounted) {
        setState(() {
          _error = 'Not authenticated';
          _isLoading = false;
        });
      }
      return;
    }

    // Refresh token if expired
    final tokenRefreshed = await authProvider.refreshTokenIfNeeded();
    if (!tokenRefreshed) {
      print('🔍 [ProfileHeader] Token refresh failed');
      if (mounted) {
        setState(() {
          _error = 'Session expired. Please login again.';
          _isLoading = false;
        });
      }
      return;
    }

    // Set token
    if (authProvider.session != null) {
      apiService.setToken(authProvider.session!.accessToken);
      print('🔍 [ProfileHeader] Token set');
    } else {
      print('🔍 [ProfileHeader] No session after refresh');
      if (mounted) {
        setState(() {
          _error = 'Not authenticated';
          _isLoading = false;
        });
      }
      return;
    }

    final userId = widget.userId ?? authProvider.user?.id;
    print('🔍 [ProfileHeader] UserId: $userId');
    if (userId == null) {
      print('🔍 [ProfileHeader] User ID is null');
      if (mounted) {
        setState(() {
          _error = 'User not found';
          _isLoading = false;
        });
      }
      return;
    }

    try {
      print('🔍 [ProfileHeader] Calling getProfileById for: $userId');
      final profile = await apiService.getProfileById(userId);
      print(
          '🔍 [ProfileHeader] Profile loaded: ${profile.fullName ?? "No name"}');
      if (mounted && _lastUserId == userId) {
        setState(() {
          _profile = profile;
          _isLoading = false;
          _hasLoaded = true;
        });
        print('🔍 [ProfileHeader] Profile state updated');
      }
    } catch (e, stackTrace) {
      print('🔍 [ProfileHeader] Error loading profile: $e');
      print('🔍 [ProfileHeader] Stack trace: $stackTrace');
      if (mounted && _lastUserId == userId) {
        // Extract clean error message
        String errorMessage = 'Failed to load profile';
        if (e is Exception) {
          final message = e.toString();
          // Remove "Exception: " prefix if present
          if (message.startsWith('Exception: ')) {
            errorMessage = message.substring(11);
          } else {
            errorMessage = message;
          }
        }

        setState(() {
          _error = errorMessage;
          _isLoading = false;
          _hasLoaded = true;
        });
        print('🔍 [ProfileHeader] Error state set: $errorMessage');
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    print(
        '🔍 [ProfileHeader] Building. isLoading: $_isLoading, error: $_error, profile: ${_profile != null}');

    if (_isLoading) {
      print('🔍 [ProfileHeader] Showing loading indicator');
      return Container(
        padding: const EdgeInsets.all(SyntrakSpacing.lg),
        child: const Center(
          child: CircularProgressIndicator(),
        ),
      );
    }

    if (_error != null) {
      print('🔍 [ProfileHeader] Showing error: $_error');
      return Container(
        padding: const EdgeInsets.all(SyntrakSpacing.lg),
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'Error: $_error',
                style: SyntrakTypography.bodyMedium.copyWith(
                  color: SyntrakColors.error,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: SyntrakSpacing.md),
              ElevatedButton(
                onPressed: () {
                  _hasLoaded = false;
                  _loadProfile();
                },
                child: const Text('Retry'),
              ),
            ],
          ),
        ),
      );
    }

    if (_profile == null) {
      print('🔍 [ProfileHeader] Profile is null, showing empty');
      return Container(
        padding: const EdgeInsets.all(SyntrakSpacing.lg),
        child: const Center(
          child: Text('No profile data available'),
        ),
      );
    }

    final profile = _profile!;
    final displayName = profile.fullName ?? 'User';
    final username = profile.username ?? '';

    print('🔍 [ProfileHeader] Rendering profile: $displayName (@$username)');

    return Container(
      padding: const EdgeInsets.all(SyntrakSpacing.lg),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border(
          bottom: BorderSide(
            color: Colors.grey[200]!,
            width: 0.5,
          ),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Avatar and action buttons row
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Avatar (circular, 80x80 pixels)
              CircleAvatar(
                radius: 40,
                backgroundColor: SyntrakColors.primary.withOpacity(0.2),
                backgroundImage: profile.avatarUrl != null
                    ? NetworkImage(profile.avatarUrl!)
                    : null,
                child: profile.avatarUrl == null
                    ? Text(
                        displayName.isNotEmpty
                            ? displayName[0].toUpperCase()
                            : 'U',
                        style: SyntrakTypography.headlineMedium.copyWith(
                          color: SyntrakColors.primary,
                          fontWeight: FontWeight.bold,
                        ),
                      )
                    : null,
              ),
              const Spacer(),
              // Action buttons
              Row(
                children: [
                  // Edit Profile button (only for current user)
                  if (widget.userId == null)
                    TextButton.icon(
                      onPressed: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => const EditProfileScreen(),
                          ),
                        );
                      },
                      icon: const Icon(Icons.edit, size: 18),
                      label: const Text('Edit Profile'),
                      style: TextButton.styleFrom(
                        foregroundColor: SyntrakColors.primary,
                      ),
                    ),
                  const SizedBox(width: SyntrakSpacing.sm),
                  // Share Profile button (placeholder)
                  IconButton(
                    onPressed: () {
                      // TODO: Implement share functionality
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                            content: Text('Share profile (coming soon)')),
                      );
                    },
                    icon: const Icon(Icons.share),
                    color: SyntrakColors.textSecondary,
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(height: SyntrakSpacing.md),
          // Full name (large bold text)
          Text(
            displayName,
            style: SyntrakTypography.headlineSmall.copyWith(
              fontWeight: FontWeight.bold,
              color: SyntrakColors.textPrimary,
            ),
          ),
          // Username (secondary text)
          if (username.isNotEmpty) ...[
            const SizedBox(height: SyntrakSpacing.xs),
            Text(
              '@$username',
              style: SyntrakTypography.bodyMedium.copyWith(
                color: SyntrakColors.textSecondary,
              ),
            ),
          ],
          // Bio (leading text below name)
          if (profile.bio != null && profile.bio!.isNotEmpty) ...[
            const SizedBox(height: SyntrakSpacing.md),
            Text(
              profile.bio!,
              style: SyntrakTypography.bodyMedium.copyWith(
                color: SyntrakColors.textPrimary,
                height: 1.4,
              ),
            ),
          ],
          // Additional info (ski level, home)
          if (profile.skiLevel != null || profile.home != null) ...[
            const SizedBox(height: SyntrakSpacing.md),
            Wrap(
              spacing: SyntrakSpacing.md,
              runSpacing: SyntrakSpacing.sm,
              children: [
                if (profile.skiLevel != null)
                  Chip(
                    label: Text(profile.skiLevel!),
                    backgroundColor: SyntrakColors.primary.withOpacity(0.1),
                    labelStyle: SyntrakTypography.labelSmall.copyWith(
                      color: SyntrakColors.primary,
                    ),
                    padding: const EdgeInsets.symmetric(
                      horizontal: SyntrakSpacing.sm,
                      vertical: SyntrakSpacing.xs,
                    ),
                  ),
                if (profile.home != null)
                  Chip(
                    label: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Icon(Icons.location_on, size: 14),
                        const SizedBox(width: 4),
                        Text(profile.home!),
                      ],
                    ),
                    backgroundColor: SyntrakColors.secondary.withOpacity(0.1),
                    labelStyle: SyntrakTypography.labelSmall.copyWith(
                      color: SyntrakColors.secondary,
                    ),
                    padding: const EdgeInsets.symmetric(
                      horizontal: SyntrakSpacing.sm,
                      vertical: SyntrakSpacing.xs,
                    ),
                  ),
              ],
            ),
          ],
        ],
      ),
    );
  }
}
