import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:syntrak/core/auth/authenticated_session.dart';
import 'package:syntrak/core/di/service_locator.dart';
import 'package:syntrak/core/errors/app_result.dart';
import 'package:syntrak/core/logging/app_logger.dart';
import 'package:syntrak/core/theme.dart';
import 'package:syntrak/models/profile.dart';
import 'package:syntrak/providers/auth_provider.dart';
import 'package:syntrak/services/profile_service.dart';
import 'package:syntrak/screens/profile/edit_profile_screen.dart';

/// ProfileHeader is a widget that displays the profile information at the top of the profile screen
/// use query to fetch and cache profile information from the backend

class ProfileHeader extends StatefulWidget {
  final String? userId; // If null, shows current user's profile
  // profile header widget = used to display the profile information

  const ProfileHeader({
    super.key,

    /// key for the widget, generated by the framework
    this.userId,
  });

  @override

  /// change the behavior of methods in a child class that were originially defined in a parent class
  State<ProfileHeader> createState() => _ProfileHeaderState();
}

class _ProfileHeaderState extends State<ProfileHeader> {
  final ProfileService _profileService = sl<ProfileService>();
  Profile? _profile;
  bool _isLoading = true;
  String? _error;
  bool _hasLoaded = false;
  String? _lastUserId;

  @override
  void initState() {
    super.initState();
    _lastUserId = widget.userId;
    _loadProfile();
  }

  @override
  void didUpdateWidget(ProfileHeader oldWidget) {
    super.didUpdateWidget(oldWidget);
    // Only reload if userId changed
    if (oldWidget.userId != widget.userId) {
      _lastUserId = widget.userId;
      _hasLoaded = false;
      _loadProfile();
    }
  }

  Future<void> _loadProfile() async {
    // Prevent multiple simultaneous loads
    if (_isLoading && _hasLoaded) {
      AppLogger.instance.debug('[ProfileHeader] Skipping load - already loading and loaded');
      return;
    }

    AppLogger.instance.debug('[ProfileHeader] Loading profile...');
    setState(() {
      _isLoading = true;
      _error = null;
    });

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final sessionOutcome = await ensureAuthenticatedSession(
      authProvider,
      viewUserId: widget.userId,
      requireUserId: true,
    );
    late final String userId;
    switch (sessionOutcome) {
      case AuthenticatedSessionError(:final message):
        if (mounted) {
          setState(() {
            _error = message;
            _isLoading = false;
          });
        }
        return;
      case AuthenticatedSessionOk(:final resolvedUserId):
        userId = resolvedUserId!;
    }

    AppLogger.instance.debug('[ProfileHeader] Calling getProfileById for: $userId');
    final profileResult = await _profileService.getProfileById(userId);
    switch (profileResult) {
      case AppSuccess(:final value):
        final profile = value;
        AppLogger.instance.debug('[ProfileHeader] Profile loaded: ${profile.fullName ?? "No name"}');
        if (mounted && _lastUserId == userId) {
          setState(() {
            _profile = profile;
            _isLoading = false;
            _hasLoaded = true;
          });
          AppLogger.instance.debug('[ProfileHeader] Profile state updated');
        }
      case AppFailure(:final error):
        AppLogger.instance.debug('[ProfileHeader] Error loading profile: ${error.userMessage}');
        if (mounted && _lastUserId == userId) {
          setState(() {
            _error = error.userMessage;
            _isLoading = false;
            _hasLoaded = true;
          });
          AppLogger.instance.debug('[ProfileHeader] Error state set: ${error.userMessage}');
        }
    }
  }

  @override
  Widget build(BuildContext context) {
    AppLogger.instance.debug('[ProfileHeader] Building. isLoading: $_isLoading, error: $_error, profile: ${_profile != null}');

    if (_isLoading) {
      AppLogger.instance.debug('[ProfileHeader] Showing loading indicator');
      return Container(
        padding: const EdgeInsets.all(SyntrakSpacing.lg),
        child: const Center(
          child: CircularProgressIndicator(),
        ),
      );
    }

    if (_error != null) {
      AppLogger.instance.debug('[ProfileHeader] Showing error: $_error');
      return Container(
        padding: const EdgeInsets.all(SyntrakSpacing.lg),
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'Error: $_error',
                style: SyntrakTypography.bodyMedium.copyWith(
                  color: SyntrakColors.error,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: SyntrakSpacing.md),
              ElevatedButton(
                onPressed: () {
                  _hasLoaded = false;
                  _loadProfile();
                },
                child: const Text('Retry'),
              ),
            ],
          ),
        ),
      );
    }

    if (_profile == null) {
      AppLogger.instance.debug('[ProfileHeader] Profile is null, showing empty');
      return Container(
        padding: const EdgeInsets.all(SyntrakSpacing.lg),
        child: const Center(
          child: Text('No profile data available'),
        ),
      );
    }

    final profile = _profile!;
    final displayName = profile.fullName ?? 'User';
    final username = profile.username ?? '';

    AppLogger.instance.debug('[ProfileHeader] Rendering profile: $displayName (@$username)');

    return Container(
      padding: const EdgeInsets.all(SyntrakSpacing.lg),
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border(
          bottom: BorderSide(
            color: Colors.grey[200]!,
            width: 0.5,
          ),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Avatar and action buttons row
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Avatar (circular, 80x80 pixels)
              CircleAvatar(
                radius: 40,
                backgroundColor: SyntrakColors.primary.withOpacity(0.2),
                backgroundImage: profile.avatarUrl != null
                    ? NetworkImage(profile.avatarUrl!)
                    : null,
                child: profile.avatarUrl == null
                    ? Text(
                        displayName.isNotEmpty
                            ? displayName[0].toUpperCase()
                            : 'U',
                        style: SyntrakTypography.headlineMedium.copyWith(
                          color: SyntrakColors.primary,
                          fontWeight: FontWeight.bold,
                        ),
                      )
                    : null,
              ),
              const Spacer(),
              // Action buttons
              Row(
                children: [
                  // Edit Profile button (only for current user)
                  if (widget.userId == null)
                    TextButton.icon(
                      onPressed: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => const EditProfileScreen(),
                          ),
                        );
                      },
                      icon: const Icon(Icons.edit, size: 18),
                      label: const Text('Edit Profile'),
                      style: TextButton.styleFrom(
                        foregroundColor: SyntrakColors.primary,
                      ),
                    ),
                  const SizedBox(width: SyntrakSpacing.sm),
                  // Share Profile button (placeholder)
                  IconButton(
                    onPressed: () {
                      // TODO: Implement share functionality
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                            content: Text('Share profile (coming soon)')),
                      );
                    },
                    icon: const Icon(Icons.share),
                    color: SyntrakColors.textSecondary,
                  ),
                ],
              ),
            ],
          ),
          const SizedBox(height: SyntrakSpacing.md),
          // Full name (large bold text)
          Text(
            displayName,
            style: SyntrakTypography.headlineSmall.copyWith(
              fontWeight: FontWeight.bold,
              color: SyntrakColors.textPrimary,
            ),
          ),
          // Username (secondary text)
          if (username.isNotEmpty) ...[
            const SizedBox(height: SyntrakSpacing.xs),
            Text(
              '@$username',
              style: SyntrakTypography.bodyMedium.copyWith(
                color: SyntrakColors.textSecondary,
              ),
            ),
          ],
          // Bio (leading text below name)
          if (profile.bio != null && profile.bio!.isNotEmpty) ...[
            const SizedBox(height: SyntrakSpacing.md),
            Text(
              profile.bio!,
              style: SyntrakTypography.bodyMedium.copyWith(
                color: SyntrakColors.textPrimary,
                height: 1.4,
              ),
            ),
          ],
          // Additional info (ski level, home)
          if (profile.skiLevel != null || profile.home != null) ...[
            const SizedBox(height: SyntrakSpacing.md),
            Wrap(
              spacing: SyntrakSpacing.md,
              runSpacing: SyntrakSpacing.sm,
              children: [
                if (profile.skiLevel != null)
                  Chip(
                    label: Text(profile.skiLevel!),
                    backgroundColor: SyntrakColors.primary.withOpacity(0.1),
                    labelStyle: SyntrakTypography.labelSmall.copyWith(
                      color: SyntrakColors.primary,
                    ),
                    padding: const EdgeInsets.symmetric(
                      horizontal: SyntrakSpacing.sm,
                      vertical: SyntrakSpacing.xs,
                    ),
                  ),
                if (profile.home != null)
                  Chip(
                    label: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Icon(Icons.location_on, size: 14),
                        const SizedBox(width: 4),
                        Text(profile.home!),
                      ],
                    ),
                    backgroundColor: SyntrakColors.secondary.withOpacity(0.1),
                    labelStyle: SyntrakTypography.labelSmall.copyWith(
                      color: SyntrakColors.secondary,
                    ),
                    padding: const EdgeInsets.symmetric(
                      horizontal: SyntrakSpacing.sm,
                      vertical: SyntrakSpacing.xs,
                    ),
                  ),
              ],
            ),
          ],
        ],
      ),
    );
  }
}
